name: CD

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    name: Deploy to Dev EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build Spring Boot jar
        run: ./gradlew clean bootJar -x test --no-daemon

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/slatto-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/SLAT-TO-BE/build/libs/

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ubuntu/deploy/deploy.sh
            /home/ubuntu/deploy/deploy.sh